import streamlit as st
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPvkeCJNBDl_XNYxHEH14ceu90xQYeCi
"""


# กดรันแล้วจะมีปุ่ม Choose Files ขึ้นมาให้กดเลือกไฟล์ในเครื่อง
import pandas as pd

# 1. โหลดข้อมูลจากไฟล์ Excel
print("กำลังอ่านไฟล์ข้อมูล...")
df = pd.read_csv("customer_churn_clv_data.csv")
# 2. ดูตัวอย่างข้อมูล 5 แถวแรก
print("\n--- ตัวอย่างข้อมูล 5 แถวแรก ---")
st.dataframe(df.head())
# 3. ดูจำนวนแถว คอลัมน์ และประเภทข้อมูล
print("\n--- ภาพรวมของข้อมูล ---")
df_clean = df.copy()

print("--- ข้อมูลหลังทำ Data Cleaning ---")
print(f"จำนวนแถวคงเหลือ: {df_clean.shape[0]:,} แถว")
st.dataframe(df_clean.head())

st.title("E-Commerce Customer CLV & Churn Dashboard")

# แสดงข้อมูลตัวอย่าง
st.subheader("Customer Data Overview")
st.dataframe(df_clean.head(10))

# แสดงกราฟสรุป CLV
st.subheader("Top 10 High CLV Customers")
top_clv = df_clean.sort_values(by='CLV', ascending=False).head(10)
st.bar_chart(data=top_clv, x='CustomerID', y='CLV')

# บันทึกผลลัพธ์กฎความสัมพันธ์ลงไฟล์ Excel
print("บันทึกไฟล์เรียบร้อยแล้ว!")

import matplotlib.pyplot as plt
import seaborn as sns

# วาด Scatter plot แสดงความสัมพันธ์ระหว่าง Support, Confidence และ Lift
plt.figure(figsize=(8, 5))
sns.scatterplot(
    x=rules['support'],
    y=rules['confidence'],
    size=rules['lift'],
    hue=rules['lift'],
    palette='viridis',
    sizes=(20, 200)
)
plt.title('Market Basket Analysis - Support vs Confidence (Sized by Lift)')
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.grid(True)
plt.show()

import datetime as dt
import numpy as np
import pandas as pd

# 1. คำนวณตาราง RFM
snapshot_date = df_clean['InvoiceDate'].max() + dt.timedelta(days=1)

rfm = df_clean.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days, # Recency
    'InvoiceNo': 'nunique',                                  # Frequency
    'TotalSales': 'sum'                                      # Monetary
}).reset_index()

rfm.columns = ['CustomerID', 'Recency', 'Frequency', 'Monetary']

# 2. กำหนดเป้าหมาย Churn ( Recency > 90 วัน คือ Churn = 1 )
rfm['Churn'] = np.where(rfm['Recency'] > 90, 1, 0)
rfm['CLV'] = rfm['Monetary']

# 3. แสดงผลรวมจำนวนลูกค้าแยกตามสถานะ
print("--- จำนวนลูกค้าแยกตาม Churn Status ---")
print(rfm['Churn'].value_counts().rename({0: 'Active (ยังซื้ออยู่)', 1: 'Churned (เลิกซื้อ)'}))
display(rfm.head())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score

# 1. จัดเตรียม Features (ปัจจัยในการทำนาย) และ Target (ผลลัพธ์ Churn)
X = rfm[['Recency', 'Frequency', 'Monetary']]
y = rfm['Churn']

# 2. แบ่งข้อมูลสำหรับ Train 80% และ Test 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. สร้างและเทรน Model ด้วย Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. ทำนายเปอร์เซ็นต์ความเสี่ยง Churn Risk (%) ให้กับลูกค้าทุกคน
rfm['Churn_Risk_%'] = (model.predict_proba(X)[:, 1] * 100).round(2)

# 5. บันทึกผลลัพธ์เป็นไฟล์ CSV เพื่อเตรียมนำไปใช้ทำ Streamlit Dashboard
rfm.to_csv("customer_churn_clv_data.csv", index=False)

print("--- บันทึกไฟล์ customer_churn_clv_data.csv เรียบร้อยแล้ว! ---")
print("\n--- ตัวอย่าง 10 อันดับลูกค้าที่มีความเสี่ยง Churn สูงสุด ---")
display(rfm.sort_values(by='Churn_Risk_%', ascending=False).head(10))


# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Customer CLV & Churn Dashboard", layout="wide")
# 
# st.title("📊 E-Commerce Customer CLV & Churn Risk Engine")
# st.markdown("แดชบอร์ดวิเคราะห์มูลค่าลูกค้า (CLV) และความเสี่ยงในการเลิกซื้อ (Churn Risk)")
# 
# # โหลดข้อมูล
# @st.cache_data
# def load_data():
#     return pd.read_csv("customer_churn_clv_data.csv")
# 
# df = load_data()
# 
# # Summary Metrics
# col1, col2, col3, col4 = st.columns(4)
# col1.metric("จำนวนลูกค้าทั้งหมด", f"{len(df):,} คน")
# col2.metric("ยอดขายรวม (CLV Total)", f"${df['CLV'].sum():,.2f}")
# col3.metric("เสี่ยง Churn สูง (>70%)", f"{len(df[df['Churn_Risk_%'] > 70]):,} คน")
# col4.metric("อัตรา Churn โดยรวม", f"{(df['Churn'].mean()*100):.1f}%")
# 
# st.markdown("---")
# 
# # Section: Risk Distribution & Top High-Risk Customers
# c1, c2 = st.columns(2)
# 
# with c1:
#     st.subheader("🎯 การกระจายตัวของความเสี่ยง Churn")
#     fig = px.histogram(df, x="Churn_Risk_%", nbins=20, title="จำนวนลูกค้าแยกตาม % ความเสี่ยง", color_discrete_sequence=['#EF553B'])
#     st.plotly_chart(fig, use_container_width=True)
# 
# with c2:
#     st.subheader("⚠️ 10 อันดับลูกค้าเสี่ยงสูงที่ต้องเร่งรักษา (High Value & High Churn)")
#     high_risk_high_val = df.sort_values(by=['Churn_Risk_%', 'CLV'], ascending=[False, False]).head(10)
#     st.dataframe(high_risk_high_val[['CustomerID', 'Recency', 'Frequency', 'CLV', 'Churn_Risk_%']])
# 
# # Section: Customer Lookup
# st.markdown("---")
# st.subheader("🔍 ค้นหาข้อมูลรายลูกค้า (Customer Lookup)")
# cust_id = st.number_input("ใส่ CustomerID ที่ต้องการค้นหา:", value=int(df['CustomerID'].iloc[0]))
# cust_data = df[df['CustomerID'] == cust_id]
# 
# if not cust_data.empty:
#     st.write(cust_data)
# else:
#     st.warning("ไม่พบ CustomerID นี้ในระบบ")

# ดึง IP Address ของเครื่อง Colab (ต้องใช้เป็น Password ตอนเปิดลิงก์)

# รัน Streamlit ผ่าน LocalTunnel

# 1. สั่งให้ Streamlit ทำงานเบื้องหลัง

# 2. ดึง IP Address สำหรับใช้เป็น Password


# 3. เปิด Web App ผ่าน Localtunnel

# 1. รัน Streamlit ไว้ใน Background

# 2. ติดตั้งและเปิดเซิร์ฟเวอร์ด้วย cloudflared

